language: python
dist: trusty
sudo: true
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

install:
  - sudo pip install sphinx
  - sudo python setup.py install

script:
  - sudo python setup.py sdist bdist_wheel
  - sudo python setup.py build_docs -a

notifications:
    email: false

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $github_token
    local_dir: build/sphinx/html
    on:
      branch: develop
      repo: TagnumElite/yummy_sphinx_theme
      python: 3.6
  - provider: pypi
    user: $pypi_username
    password: $pypi_password
    on:
      branch: master
      python: 3.6
      repo: TagnumElite/yummy_sphinx_theme
