language: python
dist: trusty
sudo: true
python:
  - 3.6

cache:
  - npm
  - pip

before_install:
  - nvm install node
  - nvm use node

install:
  - npm ci
  - sudo pip install --upgrade pip
  - sudo pip install --upgrade requirements.txt
  - sudo python setup.py install

script:
  - sudo python setup.py sdist bdist_wheel
  - npm run build
  - cd docs && make html && cd ..

notifications:
    email: false

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $github_token
    local_dir: docs/_build/html
    on:
      branch: develop
      repo: TagnumElite/yummy_sphinx_theme
      python: 3.6
  - provider: pypi
    user: __token__
    password: $pypi_token
    on:
      branch: master
      python: 3.6
      repo: TagnumElite/yummy_sphinx_theme
